---
title: "Showing SAS errors"
author: "Doug Hemken"
date: "`r format(Sys.Date(), '%b %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Showing SAS errors}
  %\VignetteEngine{knitr::rmarkdown_notangle}
  %\VignetteEncoding{UTF-8}
---

# To see SAS errors, use chunk option `error=TRUE`.
SAS does not always exit with an error when it encounters problems, but
when it does, you should see the log in your document instead of the code.

## First, set up your SAS engine configuration.
```{r setup, message=FALSE}
library(SASmarkdown)
```

## A Semantic Error.
Semantic errors (typos etc.) cause SAS to return an error
status when SAS finishes.  Unless you tell R to allow
errors, this aborts processing your document.

In this example, try to use WORK data, without setting up data there.
SAS produces an ERROR.  (No output is produced.)

Use chunk option `error=TRUE`.

    ```{sas procmeans, error=TRUE} `r ''`
    proc means data=class;
    run;
    ```

Which produces:
```{sas procmeans, error=TRUE}
proc means data=class;
run;
```
## An Execution Error.
Division by zero produces error flags within the DATA step, but does
**not** cause SAS to return an error code when it finishes.  So even
if we allow for errors, the `sas` engine gives us the usual output.
```{sas divzero}
data class;
    set sashelp.class(obs=5);
    age0 = age/0;
    keep age age0;
    run;

proc print data=class;
run;
```

To see the DATA step ERROR, switch to the `saslog` engine.  Here the
chunk option `error` is irrelevant.

    ```{saslog divzero, error=TRUE} `r ''`
    ```

Producing both the log and the PROC PRINT output.
```{saslog divzero, error=TRUE}
```

## Replicate in HTML.
The semantic error, where we need chunk option \"error=TRUE\".  In this
particular example, the **sas** and **sashtml** engines give us the
same result, because there is no output produced by either.
```{sashtml procmeans, error=TRUE}
```

And the execution error, where the chunk option is irrelevant.  Using 
the **sashtmllog** engine, we see both the DATA step errors and the
HTML output.
```{sashtmllog procmeans, error=TRUE}
```
